<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Internet shop</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <style>
        /* Move down content because we have a fixed navbar that is 50px tall */
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/index.php">Интернет магазин</a>
        </div>

            <?php if (isset($_SESSION['user_logged_in']) && 1 == $_SESSION['user_logged_in']) { ?>

                <form action="change.php" class="navbar-form navbar-left" method="GET">
                    <div class="form-group">
                        <select name="color" class="form-control">
                            <option <?php if ($_SESSION['color'] == 'red') { echo "selected"; } ?> value="red">Color: red</option>
                            <option <?php if ($_SESSION['color'] == 'green') { echo "selected"; } ?>  value="green">Color: green</option>
                            <option <?php if ($_SESSION['color'] == 'blue') { echo "selected"; } ?>  value="blue">Color: blue</option>
                            <option <?php if ($_SESSION['color'] == 'yellow') { echo "selected"; } ?>  value="yellow">Color: yellow</option>
                            <option  <?php if ($_SESSION['color'] == 'gray') { echo "selected"; } ?> value="gray">Color: gray</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-default">Change</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><?=$_SESSION['user_login']?></a></li>
                    <li><a  href="/logout.php">Logout</a></li>
                </ul>
            <?php } else { ?>
                <?php include "login_form.phtml" ?>
            <?php } ?>



    </div>
</nav>


<div class="container">