<div id="navbar" class="navbar-collapse collapse">
<form method="POST" class="navbar-form navbar-right">
    <div class="form-group">
        <input name="user_login" type="text" placeholder="Login" class="form-control">
    </div>
    <div class="form-group">
        <input name="user_password" type="password" placeholder="Password" class="form-control">
    </div>
    <button type="submit" class="btn btn-success">Sign in</button>
</form>
</div><!--/.navbar-collapse -->