<?php include "partials/header.phtml"  ?>

<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1>Добро пожаловать в наш интернет магазин</h1>
            <p><a class="btn btn-primary btn-lg" href="/register.php" role="button">Регистрация</a></p>
        </div>
    </div>
    <!-- Example row of columns -->

<?php include "partials/footer.phtml"  ?>