<?php include "partials/header.phtml"  ?>

    <h1>Регистрация</h1>
    <form method="POST">
        <div class="form-group">
            <label for="exampleInputEmail1">Login</label>
            <input name="user_login" type="text" class="form-control" id="exampleInputEmail1" placeholder="Login">
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Password</label>
            <input name="user_password"  type="password" class="form-control" id="exampleInputEmail1" placeholder="Password">
        </div>

        <div class="form-group">
            <button class="btn btn-primary" type="submit">Регистрация</button>
        </div>
    </form>

<?php include "partials/footer.phtml"  ?>